server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres?user=postgres&password=admin
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    schemas: school